openapi: "3.1.0"
info:
  title: "Moit151 API"
  description: "Moit151 API"
  version: "1.0.0"
servers:
  - url: "https://Moit151"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
  /api/files:
    get:
      description: ""
      security:
        - Bearer:
            - openapi
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/UploadedFile"
    post:
      description: ""
      security:
        - Bearer:
            - openapi
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UploadPresignedUrlResponse"
  /api/files/{fileId}:
    get:
      description: ""
      parameters:
        - name: "fileId"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "fileId"
          in: "path"
          required: true
          schema:
            type: "string"
      security:
        - Bearer:
            - openapi
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "FileId is empty"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "Invalid FileId"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "Invalid FileId"
        "302":
          description: "Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DownloadPresignedUrlResponse"
    put:
      description: ""
      parameters:
        - name: "fileId"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "fileId"
          in: "path"
          required: true
          schema:
            type: "string"
      security:
        - Bearer:
            - openapi
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "FileId is empty"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "Invalid FileId"
        "302":
          description: "Found"
          content:
            '*/*':
              schema:
                type: "object"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
  /api/user:
    get:
      description: ""
      security:
        - Bearer:
            - openapi
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "Invalid JWT"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "User not found"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/User"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUserRequestBody"
        required: true
      security:
        - Bearer:
            - openapi
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
              examples:
                Example#1:
                  description: ""
                  value:
                    message: "Username already taken"
                Example#2:
                  description: ""
                  value:
                    message: "External Id already taken"
                Example#3:
                  description: ""
                  value:
                    message: "Invalid JWT"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "User added"
components:
  securitySchemes:
    Bearer:
      type: oauth2
      description: JWT Token from Auth0
      flows:
        implicit:
          authorizationUrl: https://ewan.au.auth0.com/authorize?audience=https://ewan/api
          scopes:
            openid: Open Id
  schemas:
    UploadedFile:
      type: "object"
      properties:
        uploadUri:
          type: "string"
      required:
        - "uploadUri"
    UploadPresignedUrlResponse:
      type: "object"
      properties:
        url:
          type: "string"
        fileId:
          type: "string"
      required:
        - "url"
        - "fileId"
    Response:
      type: "object"
      properties:
        message:
          type: "string"
      required:
        - "message"
    DownloadPresignedUrlResponse:
      type: "object"
      properties:
        url:
          type: "string"
      required:
        - "url"
    User:
      type: "object"
      properties:
        username:
          type: "string"
        externalId:
          type: "string"
      required:
        - "username"
        - "externalId"
    NewUserRequestBody:
      type: "object"
      properties:
        username:
          type: "string"
      required:
        - "username"